" ~/.config/vim/vimrc

""" Make Vim works like before having ~/.vim/vimrc. This will set
""" 'compatible' off, switch on syntax highlighting and a few more things.
unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

""" Plugins
call plug#begin('~/.config/vim/plugged')
"" Colorscheme (PaperColor)
Plug 'https://github.com/NLKNguyen/papercolor-theme.git'
"" Copilot
Plug 'https://github.com/github/copilot.vim.git'
"" SCVim (SuperCollider)
Plug 'https://github.com/supercollider/scvim.git', { 'for': 'supercollider' }
"" Simplenote
Plug 'https://github.com/simplenote-vim/simplenote.vim.git'
"" Syntax (Hyprland)
Plug 'https://github.com/theRealCarneiro/hyprland-vim-syntax.git', { 'for': 'hypr' }
"" Syntax (Tridactyl)
Plug 'https://github.com/tridactyl/vim-tridactyl.git', { 'for': 'tridactyl' }
"" vim-smoothie
Plug 'https://github.com/psliwka/vim-smoothie.git', { 'on': [] }
call plug#end()

""" General Settings
""
set title
set hlsearch
set ignorecase
set smartcase
set nowrap
set number
set splitright
set splitbelow
"
"" Set terminal title to this titlestring
"set title titlestring=%t%(\ %M%)%(\ (%{expand(\"%:~:.:h\")})%)%(\ %a%)
"
"" Set indentation guidelines chars
"set list
"set listchars=tab:⎽⎽⏌,lead:⎽,trail:·

""" Look and feel
""
"set t_Co=256
set termguicolors
colorscheme PaperColor
if strftime("%H") < 18 && strftime("%H") > 07
	set background=light
else
	set background=dark
endif
if &diff | colorscheme evening | set diffopt=filler,context:1000000 | endif

""" General Maps & Autocommands
""
"" Open the current file with F12 in Firefox
map <silent> <F12> :!firefox % <enter><enter>
"
"" Copy from the current buffer to Wayland clipboard (wl-copy)
map <silent> <F10> :w !wl-copy -n <CR><CR>
"
"" Count the total number of words in the current buffer or visual selection
map <silent> <F9> :w !wc -w <CR>
"
"" Executes the import-gsettings script when the settings.ini file is saved
autocmd BufWritePost $HOME/.config/gtk-3.0/settings.ini silent! !import-gsettings

""" Highlight the current cursor coordinate
"" and highlight it only in the active window.
set cursorline
set cursorcolumn
highlight CursorLine ctermfg=NONE ctermbg=NONE cterm=underline,italic
au WinEnter * setlocal cursorline cursorcolumn
au WinLeave * setlocal nocursorline nocursorcolumn
au InsertEnter * highlight CursorLine ctermfg=NONE ctermbg=NONE cterm=NONE
au InsertLeave * highlight CursorLine ctermfg=NONE ctermbg=NONE cterm=underline,italic
au InsertEnter * highlight CursorColumn ctermfg=NONE ctermbg=NONE cterm=bold
au InsertLeave * highlight CursorColumn ctermfg=NONE ctermbg=DarkGray cterm=NONE

""" Tweaks for Foot terminal (https://codeberg.org/dnkl/foot/wiki#vim)
"" Enable 24-bit colors
let &t_8f = "\<Esc>[38:2::%lu:%lu:%lum"
let &t_8b = "\<Esc>[48:2::%lu:%lu:%lum"
"" Enable native mouse support
set mouse=a
set ttymouse=sgr
"" Workaround bug in vim, where it incorrectly thinks modifyOtherKeys level 2 is
"" enabled, even when it's not. The snippets below ensure modifyOtherKeys=2 is
"" enabled. https://github.com/vim/vim/issues/9014
"let &t_TI = "\<Esc>[>4;2m"
"let &t_TE = "\<Esc>[>4;m"

""" FileType settings
""
"" HTML FileType setting
au FileType html setlocal tabstop=8 softtabstop=2 shiftwidth=2 noexpandtab autoindent wrap smoothscroll linebreak
au BufNewFile *.html 0r ~/Templates/skeleton.html
"" JSON FileType setting
au FileType json setlocal tabstop=4 shiftwidth=4 noexpandtab autoindent
"" SH FileType setting
au FileType sh setlocal tabstop=4 shiftwidth=4 noexpandtab autoindent
au BufNewFile *.sh 0r ~/Templates/skeleton.sh
"" SVG FileType setting
au FileType svg setlocal tabstop=8 softtabstop=2 shiftwidth=2 noexpandtab autoindent
au BufNewFile *.svg 0r ~/Templates/skeleton.svg | 2

""" Plugin Settings
""
"" Copilot
function! ToggleCopilot()
	if copilot#Enabled()
		Copilot disable
	else
		Copilot enable
	endif
	Copilot status
endfunction
inoremap <F1> <Esc>:call ToggleCopilot()<CR>a
nnoremap <F1> :call ToggleCopilot()<CR>
"
"" Simplenote
source $HOME/.config/vim/simplenoterc.vim
"
"" SuperCollider
au BufEnter,BufWinEnter,BufNewFile,BufRead *.sc,*.scd set filetype=supercollider
"au Filetype supercollider packadd scvim
" let g:sclangTerm = "foot"
let g:sclangTerm = "st"
let g:scFlash = 1
"
"" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0
let g:syntastic_mode_map = { "mode": "passive" }
" nnoremap <F12> :SyntasticCheck<CR>
