# Adds more common rates
context.properties = {
    # https://wiki.archlinux.org/title/PipeWire#Changing_the_allowed_sample_rate(s)
    default.clock.allowed-rates = [ 32000 44100 48000 88200 96000 176400 192000 ]
}
