-- ~/.config/hypr/hyprland.conf
--
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
-- Hyprland 0.55+ usa configuración Lua; hyprlang es obsoleto.

local mod = "SUPER"
local terminal = "footclient"
local floatingTerminal = terminal .. " -a floating-foot -e tmux new-session -A -s Scratchpad"
local fileManager = terminal .. " -a Yazi bash -c \"yazi\""
-- $fileManager = $terminal -a Yazi bash -c "env YAZI_LOG=debug yazi"
local menu = "~/.config/rofi/launcher.sh"
local bar = "togglewaybar.sh"
local editor = "nvim"


-- https://wiki.hypr.land/Configuring/Basics/Monitors/
-- monitor = name, resolution, position, scale, transform, 0
-- monitor = ,preferred,auto,auto,transform,0
-- monitor = ,preferred,auto,1,mirror, LVDS-1
-- monitor = LVDS-1, 1366x768@60, 0x0, 1, transform, 0
-- monitor = LVDS-1, disable
-- monitor = VGA-1, 1680x1050@60, 1366x0, 1, transform, 1
-- monitor = HDMI-A-1, 1680x1050@60, -1050x-912, 1, transform, 1
-- monitor = HDMI-A-1, 1680x1050@60, 1366x-912, 1, transform, 1
-- monitor = HDMI-A-1, disable

hl.monitor({
    output = "HDMI-A-2",
    mode = "1680x1050@60",
    -- mode = "1920x1080@60",
    position = "auto-center-right",
    scale = 1,
    transform = 1,
})

-- Plug-and-play any monitors not specified with an explicit rule
-- automatically preferred resolution and placed on the right of the other(s)
hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = 1,
})


-- https://wiki.hypr.land/Configuring/Basics/Autostart/
-- exec-once = pcmanfm -d
-- exec-once = swaybg --output LVDS-1 --mode fill --image /usr/share/backgrounds/fgm.png
-- exec-once = swaybg --output HDMI-A-1 --mode fit --color 000000 --image /usr/share/backgrounds/pluto-portrait-enhanced-color.png
hl.on("hyprland.start", function()
	-- hl.exec_cmd("pcmanfm -d")
    hl.exec_cmd("foot --server")
    hl.exec_cmd(bar)

	-- hl.exec_cmd("swaybg --output LVDS-1 --mode fill --image /usr/share/backgrounds/fgm.png")
	-- hl.exec_cmd("swaybg --output HDMI-A-1 --mode fit --color 000000 --image /usr/share/backgrounds/pluto-portrait-enhanced-color.png")
	hl.exec_cmd("swaybg --output eDP-1 --mode fill --image /usr/share/backgrounds/fgm.png")
	hl.exec_cmd("swaybg --output HDMI-A-2 --mode fit --color 000000 --image /usr/share/backgrounds/pluto-portrait-enhanced-color.png")

	-- https://wiki.archlinux.org/title/GNOME/Keyring#Using_gnome-keyring-daemon_outside_desktop_environments_(KDE,_GNOME,_XFCE,_...)
    hl.exec_cmd("dbus-update-activation-environment DISPLAY XAUTHORITY WAYLAND_DISPLAY")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")

end)


-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/
hl.env("TERMINAL", terminal)
hl.env("EDITOR", editor)
hl.env("PAGER", "bat -p")
hl.env("BROWSER", "firefox")

-- env = GDK_BACKEND,wayland,x11,*
-- env = QT_QPA_PLATFORM,wayland-egl
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("CLUTTER_BACKEND", "wayland")

hl.env("_JAVA_AWT_WM_NONREPARENTING", "1")
hl.env("_JAVA_OPTIONS", "-Dawt.useSystemAAFontSettings=lcd")

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_ENABLE_HIGHDPI_SCALING", "1")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
-- env = QT_QPA_PLATFORMTHEME,qt5ct

-- env = GTK_THEME,Adwaita
-- env = XCURSOR_THEME,McMojave
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- https://wiki.archlinux.org/title/Hardware_video_acceleration#Configuring_VA-API
hl.env("LIBVA_DRIVER_NAME", "iHD")
hl.env("LIBVA_DRIVERS_PATH", "/usr/lib/dri")

-- https://wiki.hypr.land/Configuring/Basics/Variables/#general
hl.config({
    general = {
        border_size = 0,
        gaps_in = 2,
        gaps_out = 4,
        gaps_workspaces = 40,
        --col.inactive_border = rgba(595959aa)
        col = {
            inactive_border = "rgba(43485988)",
            active_border = "rgba(97d01add)",
        },
        --col.active_border = rgba(97d01add) rgba(f7d01add) rgba(d72c1add) 45deg
        --col.active_border = rgba(97d01add) rgba(d72c1add) rgba(f7d01add) 45deg
        layout = "dwindle",
        -- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/
        allow_tearing = true,
        -- https://wiki.hypr.land/Configuring/Basics/Variables/#snap
        snap = {
            enabled = true,
            window_gap = 10,
            monitor_gap = 10,
            border_overlap = false,
            respect_gaps = true,
        },
    },
})


-- https://wiki.hypr.land/Configuring/Basics/Variables/#decoration
hl.config({
    decoration = {
        rounding = 10,
        rounding_power = 4.0,
        active_opacity = 1.0,
        inactive_opacity = 0.95,
        fullscreen_opacity = 1.0,
        dim_inactive = false,
        dim_strength = 0.5,
        dim_special = 0.2,
        dim_around = 0.4,
        -- screen_shader = ~/.config/hypr/blue-light-filter.frag
        border_part_of_window = true,

        -- https://wiki.hypr.land/Configuring/Basics/Variables/#blur
        blur = {
            enabled = true,
            size = 4,
            passes = 1,
            ignore_opacity = true,
            xray = true,
            noise = 0.0117,
            contrast = 0.8916,
            brightness = 0.8172,
            vibrancy = 0.1696,
            vibrancy_darkness = 0.0,
            special = false,
            popups = false,
            input_methods = false,
        },

        -- https://wiki.hypr.land/Configuring/Basics/Variables/#shadow
        shadow = {
            enabled = true,
            range = 4,
            render_power = 4,
            sharp = false,
            color = "rgba(1a1a1aee)",
            color_inactive = "rgba(00000000)",
            offset = { 0, 0 },
            scale = 1.0,
        },
    },
})

-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
-- file:///home/macydnah/.config/hypr/conf.d/bezier.conf
-- Source: conf.d/bezier.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("lua.bezier")
hl.config({
    animations = {
        enabled = true,
        workspace_wraparound = false,

-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
    },
})

hl.animation({leaf = "windows", enabled = false, speed = 2, bezier = "default", })
hl.animation({leaf = "windowsIn", enabled = true, speed = 3, bezier = "easeOutExpo", style = "popin 0%", })
hl.animation({leaf = "windowsOut", enabled = true, speed = 2, bezier = "easeInExpo", style = "slide", })
hl.animation({leaf = "windowsMove", enabled = true, speed = 2, bezier = "easeOutExpo", })
hl.animation({leaf = "layers", enabled = true, speed = 2, bezier = "default", })
hl.animation({leaf = "layersIn", enabled = true, speed = 2, bezier = "easeOutCirc", })
hl.animation({leaf = "layersOut", enabled = true, speed = 4, bezier = "easeOutExpo", })
hl.animation({leaf = "fade", enabled = true, speed = 2, bezier = "default", })
hl.animation({leaf = "fadeIn", enabled = true, speed = 2, bezier = "easeInExpo", })
hl.animation({leaf = "fadeOut", enabled = true, speed = 2, bezier = "easeOutExpo", })
hl.animation({leaf = "fadeSwitch", enabled = true, speed = 2, bezier = "easeOutExpo", })
hl.animation({leaf = "fadeShadow", enabled = true, speed = 2, bezier = "easeOutExpo", })
hl.animation({leaf = "fadeLayersIn", enabled = true, speed = 2, bezier = "easeInCirc", })
hl.animation({leaf = "fadeLayersOut", enabled = true, speed = 2, bezier = "easeOutExpo", })
hl.animation({leaf = "border", enabled = false, speed = 2, bezier = "easeOutExpo", })
hl.animation({leaf = "borderangle", enabled = false, speed = 8, bezier = "easeInOutExpo", style = "once", })
hl.animation({leaf = "workspaces", enabled = true, speed = 2, bezier = "default", style = "slide", })
hl.animation({leaf = "workspacesIn", enabled = true, speed = 1, bezier = "easeOutExpo", style = "slidefade", })
hl.animation({leaf = "workspacesOut", enabled = true, speed = 1, bezier = "easeInExpo", style = "fade", })
hl.animation({leaf = "specialWorkspace", enabled = true, speed = 2, bezier = "overshot", style = "slidevert", })
hl.animation({leaf = "specialWorkspaceIn", enabled = true, speed = 2, bezier = "overshot", style = "slidefadevert", })
hl.animation({leaf = "specialWorkspaceOut", enabled = true, speed = 1, bezier = "easeInExpo", style = "slidefadevert", })


-- https://wiki.hypr.land/Configuring/Basics/Variables/#input
hl.config({
    input = {
        -- XKB Settings, see file:///usr/share/X11/xkb/rules/base.lst
        -- and https://wiki.hypr.land/Configuring/Basics/Variables/#input
        kb_model = "pc104",
        kb_layout = "us",
        kb_variant = "altgr-intl",
        kb_options = "",
        kb_rules = "",
        kb_file = "",

        -- Keyboard
        numlock_by_default = false,
        resolve_binds_by_sym = false,
        repeat_rate = 25,
        repeat_delay = 600,

        -- Mouse
        sensitivity = 0.0,
        accel_profile = "adaptive",
        force_no_accel = false,
        left_handed = false,
        scroll_method = "2fg",
        scroll_button = 0,
        scroll_button_lock = false,
        scroll_factor = 1.0,
        -- scroll_factor = 6.0
        natural_scroll = false,
        follow_mouse = 2,
        off_window_axis_events = 0,

        -- https://wiki.hypr.land/Configuring/Basics/Variables/#touchpad
        touchpad = {
            disable_while_typing = true,
            natural_scroll = true,
            scroll_factor = 1.3,
            middle_button_emulation = false,
            tap_button_map = "lrm",
            clickfinger_behavior = true,
            tap_to_click = true,
            drag_lock = 1,
            tap_and_drag = true,
            flip_x = false,
            flip_y = false,
            drag_3fg = 0,
        },
    },
})


hl.device({
    name = "tpps/2-ibm-trackpoint",
    enabled = true,
    sensitivity = 0.0,
    accel_profile = "adaptive",
    scroll_factor = 1.0,
    natural_scroll = true,
})

-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Gestures/
hl.config({
    gestures = {
        workspace_swipe_distance = 150,
        workspace_swipe_touch = false,
        workspace_swipe_invert = true,
        workspace_swipe_touch_invert = false,
        workspace_swipe_min_speed_to_force = 0,
        workspace_swipe_cancel_ratio = 0.0,
        workspace_swipe_create_new = false,

-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Gestures/
        -- gesture = 3, horizontal, workspace
        -- gesture = 3, up, special, magic
    },
})

-- https://wiki.hypr.land/Configuring/Basics/Variables/#group

hl.config({
    group = {
        auto_group = true,
        insert_after_current = true,
        focus_removed_window = true,
        drag_into_group = 2,
        merge_groups_on_drag = false,
        merge_groups_on_groupbar = false,
        merge_floated_into_tiled_on_groupbar = false,
        col = {
            border_active = "rgba(97d01add)",
            border_inactive = "rgba(43485988)",
        },

        -- https://wiki.hypr.land/Configuring/Basics/Variables/#groupbar
        groupbar = {
            enabled = true,
            font_family = "SF Pro Display",
            font_size = 14,
            font_weight_active = "normal",
            font_weight_inactive = "ultralight",
            gradients = true,
            height = 14,
            indicator_gap = 0,
            indicator_height = 0,
            stacked = false,
            render_titles = true,
            text_offset = 0,
            scrolling = false,
            rounding = 4,
            rounding_power = 2.0,
            gradient_rounding = 10,
            gradient_rounding_power = 4.0,
            round_only_edges = false,
            gradient_round_only_edges = true,
            text_color = "rgba(000000dd)",
            text_color_inactive = "rgba(ffffff66)",
            col = {
                active = "rgba(97d01add)",
                inactive = "rgba(43485955)",
            },
            gaps_in = 0,
            gaps_out = 0,
            keep_upper_gap = false,
        },
    },
})


-- https://wiki.hypr.land/Configuring/Basics/Variables/#misc
hl.config({
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        col = {
            splash = "rgba(ffffffff)",
        },
        font_family = "SF Pro Display",
        splash_font_family = "SF Pro Display",
        force_default_wallpaper = -1,
        vrr = 0,
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
        animate_manual_resizes = false,
        animate_mouse_windowdragging = false,
        disable_autoreload = false,
        enable_swallow = false,
        swallow_regex = "^(footclient)$",
        --swallow_exception_regex = ^()$
        mouse_move_focuses_monitor = true,
        background_color = "rgba(000000ff)",
        close_special_on_empty = true,
        on_focus_under_fullscreen = 1,
        middle_click_paste = false,
        render_unfocused_fps = 10,
        enable_anr_dialog = false,
        anr_missed_pings = 1,
    },
})

-- https://wiki.hypr.land/Configuring/Basics/Variables/#debug

hl.config({
    debug = {
        disable_logs = false,
        vfr = true,
    },
})

-- https://wiki.hypr.land/Configuring/Basics/Binds/
hl.config({
    binds = {
        workspace_back_and_forth = false,
        hide_special_on_workspace_change = true,
        allow_workspace_cycles = true,
        movefocus_cycles_fullscreen = true,
        movefocus_cycles_groupfirst = true,
        window_direction_monitor_fallback = true,
    },
})

-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/XWayland/

hl.config({
    xwayland = {
        enabled = true,
        use_nearest_neighbor = true,
        force_zero_scaling = true,
        -- https://wiki.hypr.land/Configuring/Advanced-and-Cool/XWayland/#abstract-unix-domain-socket
        create_abstract_socket = false,
    },
})


-- https://wiki.hypr.land/Configuring/Basics/Variables/#opengl
hl.config({
    opengl = {
        nvidia_anti_flicker = false,
    },
})


-- https://wiki.hypr.land/Configuring/Basics/Variables/#render
hl.config({
    render = {
        direct_scanout = 0,
        expand_undersized_textures = true,
        xp_mode = false,
        ctm_animation = 2,
        cm_enabled = true,
        send_content_type = false,
        cm_auto_hdr = 0,
    },
})


-- https://wiki.hypr.land/Configuring/Basics/Variables/#cursor
hl.config({
    cursor = {
        invisible = false,
        sync_gsettings_theme = true,
        no_hardware_cursors = 1,
        hotspot_padding = 5,
        inactive_timeout = 2,
        no_warps = false,
        persistent_warps = true,
        warp_on_change_workspace = 1,
        warp_on_toggle_special = 0,
        default_monitor = "LVDS-1",
        zoom_factor = 1.000,
        zoom_rigid = false,
        enable_hyprcursor = false,
        hide_on_key_press = false,
    },
})


-- https://wiki.hypr.land/Configuring/Basics/Variables/#ecosystem
hl.config({
    ecosystem = {
        no_update_news = true,
        no_donation_nag = true,
        enforce_permissions = false,
    },
})


-- https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/
hl.config({
    dwindle = {
        force_split = 2,
        preserve_split = true,
        use_active_for_splits = true,
    },
})
hl.bind(mod .. " + P", hl.dsp.window.pseudo())
hl.bind(mod .. " + C", hl.dsp.layout("togglesplit"))


-- https://wiki.hypr.land/Configuring/Layouts/Master-Layout/
hl.config({
    master = {
        new_status = "master",
    },
})

---------------------
---- KEYBINDINGS ----
---------------------



-- https://wiki.hypr.land/Configuring/Basics/Binds/

-- Media/Volume/Brightness Control
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("mpc toggle"))
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("mpc pause"))
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("mpc next"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("mpc cdprev"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("volfade-rs toggle-mute"))
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("volfade-rs increase 11"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("volfade-rs decrease 7"))
hl.bind("SHIFT + XF86AudioRaiseVolume", hl.dsp.exec_cmd("volfade-rs inc 1"))
hl.bind("SHIFT + XF86AudioLowerVolume", hl.dsp.exec_cmd("volfade-rs dec 1"))
hl.bind(mod .. " + F3", hl.dsp.exec_cmd("pavucontrol --tab=3"))
hl.bind(mod .. " + F2", hl.dsp.exec_cmd(terminal .. " --title 'Volume Control' -- wiremix"))
hl.bind(mod .. " + XF86AudioRaiseVolume", hl.dsp.exec_cmd("pavucontrol --tab=3"))
hl.bind(mod .. " + XF86AudioLowerVolume", hl.dsp.exec_cmd(terminal .. " --title 'Volume Control' -- wiremix"))
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("xbacklight -inc 3 -fps 60 -time 111 -perceived"), { repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("xbacklight -dec 3 -fps 60 -time 111 -perceived"), { repeating = true })
hl.bind("SHIFT + XF86MonBrightnessUp", function()
    hl.config({ decoration = { screen_shader = "" } })
end)
hl.bind("SHIFT + XF86MonBrightnessDown", function()
    hl.config({ decoration = { screen_shader = "~/.config/hypr/blue-light-filter.frag" } })
end)
hl.bind(mod .. " + XF86MonBrightnessUp", hl.dsp.dpms({ action = "on" }))
hl.bind(mod .. " + XF86MonBrightnessDown", function()
    hl.exec_cmd("sleep 1")
    hl.dispatch(hl.dsp.dpms({ action = "off" }))
end)
hl.bind(mod .. " + F7", function()
    hl.exec_cmd("sleep 1")
    hl.dispatch(hl.dsp.dpms({ action = "toggle" }))
end)
hl.bind(mod .. " + Menu", hl.dsp.exec_cmd("kblight"))

-- Keybinds/shortcuts for applications
hl.bind(mod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mod .. " + grave", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mod .. " + A", hl.dsp.exec_cmd(menu))
hl.bind(mod .. " + B", hl.dsp.exec_cmd(bar))
hl.bind(mod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mod .. " + N", hl.dsp.exec_cmd("networkmanager_dmenu"))
hl.bind(mod .. " + S", hl.dsp.exec_cmd(terminal .. " -- " .. editor .. " -c ':source ~/.config/vim/simplenoterc.vim | :SimplenoteList'"))
hl.bind(mod .. " + SHIFT + C", hl.dsp.exec_cmd(terminal .. " -D ~/.dotfiles -- " .. editor .. " -c ':lua FzfLua.files({ no_ignore=true, winopts={fullscreen=true} })'"))
hl.bind(mod .. " + SHIFT + P", hl.dsp.exec_cmd(terminal .. " -D ~/Documents/TeX/PRIMA_VERA_INTER_TERRA_EX_MACHINA -- " .. editor .. " -c ':e main.tex | :badd epígrafe.tex | :badd cantos/canto1.tex | :badd cantos/canto2.tex | :FzfLua files hidden=false winopts.fullscreen=true cwd_prompt=false prompt=PVITEM/ preview=\"bat --theme=auto:always -p\"'"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("grimblast save area ~/Pictures/Screenshots/$(date +%Y-%m-%d_%s).png"))
hl.bind("Print", hl.dsp.exec_cmd("grimblast save output ~/Pictures/Screenshots/$(date +%Y-%m-%d_%s).png"))
-- hl.bind("Print", hl.dsp.exec_cmd("/home/macydnah/Documents/UnADM/Scripts/captura-pantalla-UnADM.sh"))
-- bind = , Print, exec, /home/macydnah/Documents/UnADM/Scripts/captura-pantalla-UnADM.sh

-- Window manager functions
hl.bind(mod .. " + Q", hl.dsp.window.close())
hl.bind(mod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mod .. " + Tab", hl.dsp.focus({ workspace = "previous" }))
hl.bind(mod .. " + CTRL + I", hl.dsp.focus({ workspace = "previous" }))
hl.bind(mod .. " + space", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mod .. " + SHIFT + space", hl.dsp.window.pin({ action = "toggle" }))
-- hl.bind(mod .. " + X", hl.dsp.exec_cmd("togglehyprtab.sh"))
hl.bind(mod .. " + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload"))
hl.bind(mod .. " + SHIFT + Escape", hl.dsp.exit())

hl.bind("MOD1 + CTRL + Up", function()
    hl.monitor({ output = "eDP-1", transform = 0 })
end)
hl.bind("MOD1 + CTRL + Left", function()
    hl.monitor({ output = "eDP-1", transform = 1 })
end)
hl.bind("MOD1 + CTRL + Down", function()
    hl.monitor({ output = "eDP-1", transform = 2 })
end)
hl.bind("MOD1 + CTRL + Right", function()
    hl.monitor({ output = "eDP-1", transform = 3 })
end)

-- Submap: For a global unbinded environment
hl.bind("SUPER + ALT + CTRL + SHIFT + Return", hl.dsp.submap("nobindings"))
hl.define_submap("nobindings", function()
    hl.bind("SUPER + ALT + CTRL + SHIFT + Return", hl.dsp.submap("reset"))
end)
-- keybinds further down will be global again...

-- Submap: Resize
hl.bind(mod .. " + R", hl.dsp.submap("resize"))
hl.define_submap("resize", function()
    hl.bind("H", hl.dsp.window.resize({ x = -66, y = 0, relative = true }), { repeating = true })
    hl.bind("J", hl.dsp.window.resize({ x = 0, y = -66, relative = true }), { repeating = true })
    hl.bind("K", hl.dsp.window.resize({ x = 0, y = 66, relative = true }), { repeating = true })
    hl.bind("L", hl.dsp.window.resize({ x = 66, y = 0, relative = true }), { repeating = true })
    hl.bind("SHIFT + H", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
    hl.bind("SHIFT + J", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
    hl.bind("SHIFT + K", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })
    hl.bind("SHIFT + L", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
    hl.bind("Escape", hl.dsp.submap("reset"))
    hl.bind("CTRL + bracketleft", hl.dsp.submap("reset"))
    hl.bind("CTRL + C", hl.dsp.submap("reset"))
    hl.bind("Return", hl.dsp.submap("reset"))
    hl.bind("CTRL + J", hl.dsp.submap("reset"))
end)
-- keybinds further down will be global again...

-- Navigation
hl.bind(mod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mod .. " + J", hl.dsp.focus({ direction = "down" }))
hl.bind(mod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mod .. " + SHIFT + H", hl.dsp.window.move({ direction = "left" }))
hl.bind(mod .. " + SHIFT + J", hl.dsp.window.move({ direction = "down" }))
hl.bind(mod .. " + SHIFT + K", hl.dsp.window.move({ direction = "up" }))
hl.bind(mod .. " + SHIFT + L", hl.dsp.window.move({ direction = "right" }))
hl.bind(mod .. " + CTRL + H", hl.dsp.group.move_window({ forward = false }))
hl.bind(mod .. " + CTRL + L", hl.dsp.group.move_window({ forward = true }))
hl.bind(mod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize())

-- Switch/move workspaces with mod + [0-9] and mod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mod .. " + " .. key,             hl.dsp.focus({ workspace = i }))
    hl.bind(mod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end
hl.bind(mod .. " + SHIFT + grave", hl.dsp.window.move({ workspace = "special:magic", follow = false }))

---------------
---- RULES ----
---------------



-- https://wiki.hypr.land/Configuring/Basics/Window-Rules/#rules
-- https://wiki.hypr.land/Configuring/Basics/Window-Rules/#layer-rules
-- https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/#workspace-rules

-- Global Rules
hl.window_rule({
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

hl.workspace_rule({
    workspace = "special:magic",
    on_created_empty = floatingTerminal,
})

-- Monitor Rules
hl.workspace_rule({
    workspace = "m[HDMI-A-1]",
    gaps_in = 8,
    gaps_out = 16,
    border_size = 1,
})

-- workspace = 1, monitor:HDMI-A-1, default:true
-- workspace = 2, monitor:HDMI-A-1
-- workspace = 3, monitor:HDMI-A-1
-- workspace = 4, monitor:HDMI-A-1
-- workspace = 5, monitor:HDMI-A-1
-- workspace = 6, monitor:LVDS-1
-- workspace = 7, monitor:LVDS-1
-- workspace = 8, monitor:LVDS-1
-- workspace = 9, monitor:LVDS-1
-- workspace = 10, monitor:LVDS-1, default:true
-- workspace = 1, monitor:LVDS-1, default:true
-- workspace = 2, monitor:LVDS-1
-- workspace = 3, monitor:LVDS-1
-- workspace = 4, monitor:LVDS-1
-- workspace = 5, monitor:LVDS-1
-- workspace = 6, monitor:HDMI-A-1
-- workspace = 7, monitor:HDMI-A-1
-- workspace = 8, monitor:HDMI-A-1
-- workspace = 9, monitor:HDMI-A-1
-- workspace = 10, monitor:HDMI-A-1, default:true
-- Workspaces 1-5 → eDP-1 (1 is default)
for i = 1, 5 do
    hl.workspace_rule({ workspace = tostring(i), monitor = "eDP-1", default = (i == 1) })
end
-- Workspaces 6-10 → HDMI-A-2 (10 is default)
for i = 6, 10 do
    hl.workspace_rule({ workspace = tostring(i), monitor = "HDMI-A-2", default = (i == 10) })
end

-- firefoxd
hl.workspace_rule({
    workspace = "special:firefoxd",
    on_created_empty = "firefox --new-window about:blank",
})
hl.window_rule({
    match = {
        class = "^(firefox)$",
    },
    sync_fullscreen = false,
})
-- bind = , XF86Launch2, togglespecialworkspace, firefoxd
hl.bind("XF86Favorites", hl.dsp.workspace.toggle_special("firefoxd"))

-- file upload
hl.window_rule({
    name = "firefox-file-upload",
    match = {
        class = "^(firefox)$",
        title = "^(File Upload - .*)$",
        float = 1,
        fullscreen = 0,
    },
    size = "(monitor_w*0.7) (monitor_h*0.8)",
    center = true,
})

-- floating-editor
hl.window_rule({
    name = "floating-editor",
    match = {
        class = "^(floating-editor)$",
    },
    -- size = 675 364
    size = "(monitor_w*0.425) (monitor_h*0.405)",
    float = true,
    center = true,
    stay_focused = true,
})

-- floating-foot
hl.window_rule({
    name = "floating-foot",
    match = {
        class = "^(floating-foot)$",
    },
    -- size = 675 364
    -- float = on
    size = "(monitor_w*0.425) (monitor_h*0.405)",
    pseudo = true,
    float = false,
    no_shadow = true,
})

-- java windows
-- https://www.reddit.com/r/hyprland/comments/16rwbun/comment/k2f0nco/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
hl.window_rule({
    name = "netbeans-starting",
    match = {
        class = "^(java-lang-Thread|Apache NetBeans IDE [0-9]+)$",
        title = "^(Starting Apache NetBeans IDE)$",
        float = 1,
        fullscreen = 0,
    },
    center = true,
    stay_focused = true,
})
hl.window_rule({
    name = "netbeans-main-window",
    match = {
        class = "^(Apache NetBeans IDE [0-9]+)$",
        title = "^(Apache NetBeans IDE [0-9]+|.* - Apache NetBeans IDE [0-9]+)$",
        float = 1,
        fullscreen = 0,
    },
    float = false,
})
hl.window_rule({
    name = "netbeans-popups",
    match = {
        class = "^(Apache NetBeans IDE [0-9]+)$",
        title = "^(win[0-9]+)$",
        float = 1,
        fullscreen = 0,
    },
    no_initial_focus = true,
    no_focus = true,
})

hl.window_rule({
    name = "burpsuite",
    match = {
        class = "^(burp-StartBurp)$",
        float = 1,
        fullscreen = 0,
    },
    stay_focused = false,
})

-- mpv
hl.window_rule({
    name = "mpv",
    match = {
        class = "^(mpv)$",
    },
    no_blur = true,
    no_dim = true,
    no_shadow = true,
    opaque = true,
    force_rgbx = true,
    immediate = true,
    xray = false,
})

-- pcmanfm (Copying files dialog)
hl.window_rule({
    name = "pcmanfm-copying-files-dialog",
    match = {
        class = "^(pcmanfm)$",
        title = "^(Copying files)$",
    },
    size = "675 264",
    float = true,
    center = true,
    stay_focused = false,
})

-- rofi
hl.layer_rule({
    name = "rofi",
    match = {
        namespace = "rofi",
    },
    blur = true,
    -- ignore_alpha = 0
    dim_around = true,
    xray = true,
    animation = "popin",
})

-- scrcpy
hl.window_rule({
    name = "scrcpy",
    match = {
        class = "^(scrcpy)$",
        title = "^(SM-.*)$",
    },
    -- static effects
    -- size = (monitor_w*0.32) (monitor_h*0.99)
    -- pseudo = on
    -- no_initial_focus = on
    -- dynamic effects
    keep_aspect_ratio = true,
    nearest_neighbor = true,
})

-- smart gaps
-- source = conf.d/smart-gaps.conf

-- swayimg
-- windowrule {
-- 	name = swayimg
-- 	match:class = ^(swayimg.*)$
--
-- 	immediate = 1
-- }

-- Unlock Login Keyring
hl.window_rule({
    name = "unlock-login-keyring",
    match = {
        class = "^(gcr-prompter)$",
        float = 1,
        fullscreen = 0,
    },
    stay_focused = true,
})

-- Volume Control
hl.window_rule({
    name = "volume-control",
    match = {
        class = "^(org.pulseaudio.pavucontrol|foot|footclient)$",
        title = "^Volume Control$",
    },
    -- static effects
    size = "(monitor_w*0.425) (monitor_h*0.405)",
    float = true,
    center = true,
    -- dynamic effects
    stay_focused = true,
    keep_aspect_ratio = true,
    nearest_neighbor = true,
})

-- waybar
hl.layer_rule({
    name = "waybar",
    match = {
        namespace = "waybar",
    },
    blur = true,
    blur_popups = true,
    -- ignore_alpha = 0
    animation = "slide",
    xray = true,
})

-- V4L2 Viewer
hl.window_rule({
    name = "v4l2-viewer-webcam",
    match = {
        class = "^(qvidcap|qv4l2)$",
        title = "^(V4L2 Viewer|V4L2 Capture.*)$",
    },

    -- static effects
    size = "320 240",
    -- move = (monitor_w*0.82) (monitor_h*0.76)
    move = "(monitor_w*0.8125) (monitor_h*0.741)",
    float = true,
    -- center = on
    -- pseudo = on
    no_initial_focus = true,
    pin = true,

    -- dynamic effects
    -- border_size = 1
    border_size = 0,
    -- rounding = 0
    -- rounding_power = 0
    keep_aspect_ratio = true,
    nearest_neighbor = true,
    no_blur = true,
    no_dim = true,
    no_focus = true,
    no_shadow = true,
    opaque = true,
    force_rgbx = true,
    xray = false,
})

-- Show Me The Key
hl.window_rule({
    name = "show-me-the-key",
    match = {
        class = "^(one.alynx.showmethekey)$",
        title = "^(Floating Window - Show Me The Key)$",
    },
    -- static effects
    -- size = ((monitor_w)-(monitor_w/3)) (monitor_h*0.04)
    -- size = (monitor_w) (monitor_h*0.04)
    -- move = 1 (monitor_h)
    size = "320 48",
    -- move = (monitor_w*0.82) (monitor_h*0.94)
    -- move = (monitor_w*0.8125) (monitor_h*0.92)
    move = "(monitor_w*0.8125) (monitor_h*0.919)",
    float = true,
    -- center = on
    -- pseudo = on
    no_initial_focus = true,
    pin = true,

    -- dynamic effects
    border_size = 0,
    -- rounding = 0
    -- rounding_power = 0
    keep_aspect_ratio = true,
    nearest_neighbor = true,
    no_blur = true,
    no_dim = true,
    no_focus = true,
    no_shadow = true,
    opaque = false,
    force_rgbx = false,
    xray = false,
})

-- yazi
hl.window_rule({
	name = "yazi",
    match = {
        class = "^(Yazi)$",
    },
    border_color = "rgb(16b1fb)",  -- azul ANSI de yazi = regular4 de foot
})


-- Battery friendly config patches
-- Source: conf.d/battery-friendly.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("lua.battery-friendly")

-- vim: ft=lua ts=4 sts=0 sw=4 noet ai
