-- ~/.config/hypr/lua/battery-friendly.lua

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: conf.d/smart-gaps.conf
hl.config({
    general = {
        border_size = 1,
        gaps_in = 0,
        gaps_out = 0,
        gaps_workspaces = 0,
        -- col.inactive_border = rgba(434859ff) # fully opaque
        -- col.inactive_border = rgba(43485955) # not fully opaque
        -- col.inactive_border = rgba(000000ff) # fully opaque
        col = {
            inactive_border = "rgba(000000f8)", -- not fully opaque
            active_border = "rgba(97d01aff)", -- fully opaque
        },
    },
    decoration = {
        rounding = 0,
        rounding_power = 0.0,
        -- rounding = 12,
        -- rounding_power = 4.0,
        active_opacity = 1.0,
        inactive_opacity = 0.95,
        fullscreen_opacity = 1.0,
        dim_inactive = false,
        blur = {
            enabled = false,
        },
        shadow = {
            enabled = false,
        },
    },
    animations = {
        -- enabled = false,
        enabled = true,
    },
    group = {
        col = {
            border_active = "rgba(97d01aff)", -- fully opaque
            border_inactive = "rgba(43485988)",
        },
        groupbar = {
            rounding = 0,
            rounding_power = 0.0,
            gradient_rounding = 0,
            gradient_rounding_power = 0.0,
            text_color = "rgba(000000ff)", -- fully opaque
            col = {
                active = "rgba(97d01aff)", -- fully opaque
            },
        },
    },
    misc = {
        disable_autoreload = false
    },
})

require("lua.smart-gaps")

--[[ Override any gaps by workspace rules
hl.workspace_rule({ workspace = "r[1-10]",
  gaps_in = 0,
  gaps_out = 0,
}) --]]

--[[
hl.workspace_rule({ workspace = "r[1-5]",
  gaps_in = 1,
  gaps_out = 40,
}) --]]

--[[
hl.workspace_rule({ workspace = "r[6-10]",
  gaps_in = 1,
  gaps_out = 40,
}) --]]

--[[
windowrule {
	name = active-window-border
	match:focus = true
	border_size = 1
} --]]
