[settings]
default_target_type = "symbolic"

[default]
depends = []

[default.files]
foot = "~/.config/foot"
hypr = "~/.config/hypr"
i3 = "~/.config/i3"
mpv = "~/.config/mpv"
"picom.conf" = "~/.config/picom.conf"
polybar = "~/.config/polybar"
procps = "~/.config/procps"
redshift = "~/.config/redshift"
waybar = "~/.config/waybar"
