[settings]
default_target_type = "symbolic"

[default]
depends = []

[default.files]
foot = {target = "~/.config/foot", type = "symbolic", recurse = false}
hypr = {target = "~/.config/hypr", type = "symbolic", recurse = false}
i3 = {target = "~/.config/i3", type = "symbolic", recurse = false}
mpv = {target = "~/.config/mpv", type = "symbolic", recurse = false}
"picom.conf" = "~/.config/picom.conf"
polybar = {target = "~/.config/polybar", type = "symbolic", recurse = false}
procps = {target = "~/.config/procps", type = "symbolic", recurse = false}
redshift = {target = "~/.config/redshift", type = "symbolic", recurse = false}
rofi = {target = "~/.config/rofi", type = "symbolic", recurse = false}
tmux = {target = "~/.config/tmux", type = "symbolic", recurse = false}
waybar = {target = "~/.config/waybar", type = "symbolic", recurse = false}
