[settings]
default_target_type = "symbolic"

[shell.files]
"bashrc" = "~/.bashrc"
"config/procps" = {target = "~/.config/procps", type = "symbolic", recurse = false}
"config/tmux" = {target = "~/.config/tmux", type = "symbolic", recurse = false}
"config/vim" = {target = "~/.config/vim", type = "symbolic", recurse = true}
"fzfrc" = "~/.fzfrc"
"profile" = "~/.profile"

[terminal.files]
"config/alacritty" = {target = "~/.config/alacritty", type = "symbolic", recurse = false}
"config/foot" = {target = "~/.config/foot", type = "symbolic", recurse = false}

[WUtils.files]
"config/networkmanager-dmenu" = {target = "~/.config/networkmanager-dmenu", type = "symbolic", recurse = false}
"config/rofi" = {target = "~/.config/rofi", type = "symbolic", recurse = false}
"config/swayimg" = {target = "~/.config/swayimg", type = "symbolic", recurse = false}
"config/waybar" = {target = "~/.config/waybar", type = "symbolic", recurse = false}

[X11.files]
"xinitrc" = "~/.xinitrc"
"Xresources" = "~/.Xresources"

[XUtils]
depends = ["X11"]
[XUtils.files]
"config/networkmanager-dmenu" = {target = "~/.config/networkmanager-dmenu", type = "symbolic", recurse = false}
"config/picom.conf" = "~/.config/picom.conf"
"config/polybar" = {target = "~/.config/polybar", type = "symbolic", recurse = false}
"config/redshift" = {target = "~/.config/redshift", type = "symbolic", recurse = false}
"config/rofi" = {target = "~/.config/rofi", type = "symbolic", recurse = false}


## Development ##
[rust.files]
"cargo/config.toml" = "~/.cargo/config.toml"


## File managers ##
[yazi.files]
"config/yazi" = {target = "~/.config/yazi", type = "symbolic", recurse = true}


## Firefox ##
[tridactyl.files]
"config/tridactyl" = {target = "~/.config/tridactyl", type = "symbolic", recurse = false}


## Multimedia ##
[mpv.files]
"config/mpv" = {target = "~/.config/mpv", type = "symbolic", recurse = false}
[mpv-yt]
depends = ["mpv", "yt-dlp"]
[yt-dlp.files]
"config/yt-dlp" = {target = "~/.config/yt-dlp", type = "symbolic", recurse = false}


## Neovim ##
[neovim.files]
"config/nvim" = {target = "~/.config/nvim", type = "symbolic", recurse = true}


## Wayland Compositors ##
[hyprland.files]
"config/hypr" = {target = "~/.config/hypr", type = "symbolic", recurse = false}
[sway.files]
"config/sway" = {target = "~/.config/sway", type = "symbolic", recurse = false}
#[wqtile.files]
#"config/qtile" = {target = "~/.config/qtile", type = "symbolic", recurse = false}


## X Window Managers ##
[i3]
depends = ["X11"]
[i3.files]
"config/i3" = {target = "~/.config/i3", type = "symbolic", recurse = false}

[openbox]
depends = ["X11"]
[openbox.files]
"config/openbox" = {target = "~/.config/openbox", type = "symbolic", recurse = false}

[qtile]
depends = ["X11"]
[qtile.files]
"config/qtile" = {target = "~/.config/qtile", type = "symbolic", recurse = false}


## Beware!! Select the "all" package will symlink and deploy ALL the files ##
[all.files]
"bashrc" = "~/.bashrc"
"config/alacritty" = {target = "~/.config/alacritty", type = "symbolic", recurse = false}
"config/foot" = {target = "~/.config/foot", type = "symbolic", recurse = false}
"config/hypr" = {target = "~/.config/hypr", type = "symbolic", recurse = false}
"config/i3" = {target = "~/.config/i3", type = "symbolic", recurse = false}
"config/mpv" = {target = "~/.config/mpv", type = "symbolic", recurse = false}
"config/networkmanager-dmenu" = {target = "~/.config/networkmanager-dmenu", type = "symbolic", recurse = false}
"config/nvim" = {target = "~/.config/nvim", type = "symbolic", recurse = true}
"config/openbox" = {target = "~/.config/openbox", type = "symbolic", recurse = false}
"config/picom.conf" = "~/.config/picom.conf"
"config/polybar" = {target = "~/.config/polybar", type = "symbolic", recurse = false}
"config/procps" = {target = "~/.config/procps", type = "symbolic", recurse = false}
"config/qtile" = {target = "~/.config/qtile", type = "symbolic", recurse = false}
"config/redshift" = {target = "~/.config/redshift", type = "symbolic", recurse = false}
"config/rofi" = {target = "~/.config/rofi", type = "symbolic", recurse = false}
"config/sway" = {target = "~/.config/sway", type = "symbolic", recurse = false}
"config/swayimg" = {target = "~/.config/swayimg", type = "symbolic", recurse = false}
"config/tmux" = {target = "~/.config/tmux", type = "symbolic", recurse = false}
"config/vim" = {target = "~/.config/vim", type = "symbolic", recurse = true}
"config/waybar" = {target = "~/.config/waybar", type = "symbolic", recurse = false}
"config/yt-dlp" = {target = "~/.config/yt-dlp", type = "symbolic", recurse = false}
"profile" = "~/.profile"
"xinitrc" = "~/.xinitrc"
"Xresources" = "~/.Xresources"
