[settings]
default_target_type = "symbolic"

[default]
depends = []

[default.files]
foot = {type = "symbolic", target = "~/.config/foot", recurse = false}
hypr = {type = "symbolic", target = "~/.config/hypr", recurse = false}
i3 = {type = "symbolic", target = "~/.config/i3", recurse = false}
mpv = {type = "symbolic", target = "~/.config/mpv", recurse = false}
"picom.conf" = "~/.config/picom.conf"
polybar = {type = "symbolic", target = "~/.config/polybar", recurse = false}
procps = {type = "symbolic", target = "~/.config/procps", recurse = false}
redshift = {type = "symbolic", target = "~/.config/redshift", recurse = false}
waybar = {type = "symbolic", target = "~/.config/waybar", recurse = false}
