includes = []

# Packages to deploy a Xorg environment
#packages = ["shell", "i3", "XUtils", "mpv-yt", "tridactyl", "yazi"]

# Packages to deploy a Wayland environment
packages = ["shell", "terminal", "hyprland", "WUtils", "mpv-yt", "mpd", "tridactyl", "yazi", "neovim", "rust", "zathura"]

[files]
"config/alacritty" = ""

[variables]
