includes = []

# Packages to deploy a Xorg environment
#packages = ["shell", "i3", "XUtils", "mpv-yt", "tridactyl"]

# Packages to deploy a Wayland environment
packages = ["shell", "terminal", "hyprland", "WUtils", "mpv-yt", "tridactyl"]

[files]
"config/alacritty" = ""

[variables]
